/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package problemsolving;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @Test
    void solutionIsCorrect() {
        Solution underTest = new Solution();
        assertEquals(underTest.solve(), 0);
    }
}
