/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @ParameterizedTest
    @CsvSource({
            "III, 3",
            "LVIII, 58",
            "MCMXCIV, 1994",
            "CDXX, 420"
    })
    void templateTestCases(String inputString, int expected) {
        Solution s = new Solution();
        assertEquals(expected, s.romanToInt(inputString));
    }
}
