/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

// Set up a 0000 template to copy from.
public class Solution {
    public int solve() {
        return 0;
    }

    public static void main(String[] args) {
        System.out.println("02 Add Two Numbers");
    }
}
