/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @ParameterizedTest
    @CsvSource({
            "()[]{}, true", // generic test
            "(}, false", // generic test
            "(()[], false", // extra opening bracket
            "()), false", // extra closing bracket
            ")(), false", // extra closing bracket/wrong order
            "{}[])(, false", // brackets in wrong order
            "([)], false" // wrong order of closing brackets
    })
    void test(String string, String expected) {
        Solution s = new Solution();
        assertEquals(Boolean.parseBoolean(expected), s.isValid(string));
    }
}
