/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @ParameterizedTest
    @CsvSource({
            "5, 4",
            "1, 1",
            "2, 2",
            "2, 1",
            "3, 1",
            "3, 2",
            "3, 3",
            "69420, 42069",
            "12, 10",
            "2126753390, 1702766719",
            "2147483647, 2147483647"
    })
    void templateTestCases(int n, int badVersion) {
        Solution s = new Solution(badVersion);

        assertEquals(badVersion, s.firstBadVersion(n));
    }
}
