/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @Test
    void solutionIsCorrect() {
        Solution underTest = new Solution();
        int[] actual = underTest.twoSum(new int[] { 1, 2 }, 3);
        assertEquals(actual[0], 0);
        assertEquals(actual[1], 1);
    }
}
