/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @ParameterizedTest
    @CsvSource({
            "1, 1, 2",
            "2, 2, 4",
            "1, 2, 3",
            "10, 10, 20",
    })
    void templateTestCases(int a, int b, int result) {
        Solution s = new Solution();
        assertEquals(result, s.add(a, b));
    }

    @Test
    void templateCustomTest() {
        Solution s = new Solution();
        assertEquals(3, s.add(1, 2));
    }
}
