/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.converter.ConvertWith;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @ParameterizedTest
    @CsvSource({
            "1;2;3", "4;5;6", "5;7;9",
            "10;20;30", "40;50;60", "50;70;90"
    })
    void templateTestCases(
            @ConvertWith(StringToIntArrayConverter.class) int[] nums1,
            @ConvertWith(StringToIntArrayConverter.class) int[] nums2,
            @ConvertWith(StringToIntArrayConverter.class) int[] expected) {
        Solution s = new Solution();
        int[] actual = s.add(nums1, nums2);
        assertArrayEquals(expected, actual);
    }
}
